### PR TITLE
ATintern issue #381, adding multiSet Jaccard to macro_synteny_blocks

### PR DESCRIPTION
**Pull request by ATintern**
changes to gcv to support changes to microservices

### CODE REVIEW

**Comment by ATintern** [comment]
@alancleary notices after submitting the pull request I left the .getattributes file I added when trying to get Visual Studio Code to work. Let me know if you want me to recommit without it.

**Review by alancleary — COMMENTED** [review]
Can you make another pull request that doesn't include the `.getattributes` file? If you need this to use the Docker development container on your computer, then use the technique I described in legumeinfo/microservices#43 to add it to your `.gitignore` file.

**Comment by ATintern** [comment]
@alancleary I believe I fixed everything with gcv and microservices. Please let me know if I missed something. Still getting used to the fork , branch, pull, push, and commit process. Thanks.

**Comment by alancleary** [comment]
Thanks for making those changes. I forgot to mention before that your PR should push to the "macro-metrics" branch (as outlined in the [GitHub issue](https://github.com/legumeinfo/gcv/issues/381#issuecomment-1027180013)) so it can be tested before being merged into main. Do you mind revising the PR or making a new PR to do this? Thanks!

**Comment by ATintern** [comment]
Don't mind at all. Every time I do it is practice in learning vi and the git commands. Will likely get to it Wednesday morning. Sending this from email as a test, sorry if it gets to you differently than normal.
________________________________

**Comment by alancleary** [comment]
Replaced by PR #412. Closing.

**Pull request closed without merging**
